# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{g_thang}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Paul Barry"]
  s.date = %q{2009-10-09}
  s.description = %q{A Rack-Compliant HTTP Server Implemented with GServer}
  s.email = %q{mail@paulbarry.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.mdown"
  ]
  s.files = [
    "lib/g_thang.rb",
     "lib/g_thang/http_server.rb",
     "lib/g_thang/rack_handler.rb",
     "rails_generators/g_thang/USAGE",
     "rails_generators/g_thang/g_thang_generator.rb",
     "rails_generators/g_thang/templates/g_thang.rb"
  ]
  s.homepage = %q{http://github.com/pjb3/g_thang}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A Rack-Compliant HTTP Server Implemented with GServer}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
